### PR TITLE
Fix field reads in constrain functions

### LINKED ISSUE #311: Array signal not read when emitting constraint
Current status of test [calls/return_intermediate](https://github.com/project-llzk/circom/blob/llzk/circom/tests/calls/return_intermediate.circom) shows that the expected output signal read operations are not being generated when used with the `===` operator.

### PR DESCRIPTION
**Pull request by iangneal**
Resolves https://github.com/project-llzk/circom/issues/311

- Pre-reads struct fields in constrain functions, since they're read-only in that context, rather than waiting for assign operations to generate field reads (which leads to bugs in `===` cases, per the original issue).
- Updates all affected test cases as minimally as possible

### CODE REVIEW

File: llzk_backend/src/write_chain.rs [hunk 1]
```diff
@@ -249,25 +249,12 @@ impl<'ast> WriteChain<'ast> {
...
-                &OpBuilder::new(codegen.context),
-                location,
-                expected_type,
-                self_value,
-                var,
-            )?)
-        } else {
-            fc.block_ctx.get_named_value(var).copied()
-        }
+        // Both compute and constrain functions hshould have the `var` defined:
```
Comment (tim-hoffman) [inline llzk_backend/src/write_chain.rs]:
```suggestion
        // Both compute and constrain functions should have the `var` defined:
```

File: llzk_backend/src/module.rs [hunk 2]
```diff
@@ -506,6 +506,23 @@ fn gen_template_llzk<'ast, 'ctx, T: TemplateLike>(
...
+        let field_name = field.field_name();
+        constrain_ctx.block_ctx.declare_name_if_not_present(field_name, || {
+            let readf = r#struct::readf(
+                &builder,
+                location,
+                field.field_type(),
+                constrain_func.self_value_of_constrain()?,
+                field_name,
+            )?;
+            Ok(readf)
```
Comment (tim-hoffman) [inline llzk_backend/src/module.rs]:
```suggestion
            r#struct::readf(
                &builder,
                location,
                field.field_type(),
                constrain_func.self_value_of_constrain()?,
                field_name,
            )
            .map_err(Into::into)
```

**Review by tim-hoffman — APPROVED** [review]
LGTM, just nits in the code and I only took a quick scan through the tests

**Review by tim-hoffman — APPROVED** [review]
