### PR TITLE
Implement Statement::Substitution for arrays, fix multi-dim array handling

### LINKED ISSUE #202: Implement array case for `Statement::Substitution` in `gen_llzk_in_function`
see `todo!("Generate array write operation in function")` in `llzk_backend/src/function.rs`

### PR DESCRIPTION
**Pull request by iangneal**
Also ran `cargo fmt`

Resolves #202

### CODE REVIEW

File: llzk_backend/src/shared.rs [hunk 1]
```diff
@@ -503,3 +510,18 @@ pub fn get_function_type_attribute<'c: 'a, 'a>(
...
+/// TODO: `llzk-rs` should provide this directly
+#[inline]
+pub fn get_dims<'c>(arr_ty: &ArrayType<'c>) -> Vec<Attribute<'c>> {
+    (0..arr_ty.num_dims()).map(|idx| arr_ty.dim(idx)).collect::<Vec<_>>()
+}
+
+/// Create new array type that is an array of the given sub-array type.
+#[inline]
+pub fn new_array_type<'c>(dim: Attribute<'c>, subarr_ty: &ArrayType<'c>) -> ArrayType<'c> {
+    let dims = [&[dim], get_dims(subarr_ty).as_slice()].concat();
```
Comment (tim-hoffman) [inline llzk_backend/src/shared.rs]: More idiomatic Rust:
```suggestion
    let dims: Vec<_> = std::iter::once(dim).chain(get_dims(subarr_ty).iter().copied()).collect();
```

File: llzk_backend/src/function.rs [hunk 2]
```diff
@@ -1164,44 +1192,109 @@ where
...
-                    &OpBuilder::new(&codegen.context),
-                    codegen.location_from_meta(meta),
-                    arr_ty,
-                    llzk::dialect::array::ArrayCtor::Values(&init_vals),
-                ))
+                    let arr_ty = ArrayType::new(val.r#type(), &[dim]);
+                    let init_vals = if let Ok(const_dim) = const_dim {
+                        vec![val; usize::try_from(const_dim.value())?]
+                    } else {
+                        todo!("Handle template parameter array lengths in function")
```
Comment (tim-hoffman) [inline llzk_backend/src/function.rs]:
```suggestion
                        todo!("Handle template parameter array lengths")
```

File: llzk_backend/src/function.rs [hunk 3]
```diff
@@ -1164,44 +1192,109 @@ where
...
+                            ))?;
+                            function.append_op_no_result(array::insert(
+                                location,
+                                new_arr,
+                                &[idx_val],
+                                val,
+                            ))?;
+                        }
+                    } else {
+                        todo!("Handle template parameter array lengths in function")
```
Comment (tim-hoffman) [inline llzk_backend/src/function.rs]:
```suggestion
                        todo!("Handle template parameter array lengths")
```

**Review by tim-hoffman — APPROVED** [review]
LGTM, just some minor suggestions
